require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - config/routes.rb # There's an issue with https://github.com/bbatsov/rubocop/issues/4039 here
    - db/**/*
    - vendor/**/*
    - Guardfile
    - spec/support/shared_contexts/rake.rb
    - node_modules/**/*
Rails:
  Enabled: true
Rails/FilePath:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/**/*
    - config/routes.rb
Metrics/LineLength:
  Max: 100
RedundantReturn:
  AllowMultipleReturnValues: true
